INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Alergologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Anestesiologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Angiologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cardiologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Cardiovascular', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Geral', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Plástica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Torácica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Dermatologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Endocrinologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Gastroenterologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Geriatria', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Ginecologia e Obstetrícia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Hematologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Infectologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina de Emergência', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina de Família e Comunidade', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina do Trabalho', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina Interna', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina Legal', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina Nuclear', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Nefrologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Neurologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Nutrição', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Oftalmologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Oncologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Ortopedia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Otorrinolaringologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Pediatria', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Pneumologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Psiquiatria', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Radiologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Reumatologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Urologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Terapia Intensiva', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina Esportiva', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Fisiatria', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Ginecologia Endócrina', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina Paliativa', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Bariátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Vascular', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Patologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina de Reabilitação', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Terapia Ocupacional', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina da Dor', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Psicologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Homeopatia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Acupuntura', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina Antroposófica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina Chinesa', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina Tropical', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Odontologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Ortopedia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia de Cabeça e Pescoço', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Plástica Reconstrutiva', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Endoscopia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Coloproctologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia do Aparelho Digestivo', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Dermatologia Estética', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Endocrinologia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Genética Médica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina do Sono', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina Fetal', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cardiologia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Nefrologia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Neurologia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Oncologia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Hematologia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Pneumologia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Psiquiatria Infantil', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Geriatria e Gerontologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cuidados Paliativos Pediátricos', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Nutrição Clínica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Fisioterapia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Terapia Intensiva Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Otorrinolaringologia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Torácica Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Geral Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina do Adolescente', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Infectologia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina de Família', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Epidemiologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina de Urgência', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Vascular Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina de Transportes', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Hematologia e Hemoterapia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Dermatopatologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Patologia Clínica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Robótica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Minimamente Invasiva', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cuidados de Saúde Primários', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Cirurgia Plástica Estética', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Saúde Pública', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Toxicologia', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Reumatologia Pediátrica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Neurologia do Comportamento', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina de Viagem', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Otorrinolaringologia Oncológica', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Medicina Legal e Forense', NULL);
INSERT INTO especialidade (esp_nome, esp_descr) VALUES ('Oftalmologia Pediátrica', NULL);
