insert into pais values(1,"Brasil");
insert into pais values(2,"Afeganistão");
insert into pais values(3,"África do Sul");
insert into pais values(4,"Albânia, República da");
insert into pais values(5,"Alemanha");
insert into pais values(6,"Andorra");
insert into pais values(7,"Angola");
insert into pais values(8,"Anguilla");
insert into pais values(9,"Antigua Barbuda");
insert into pais values(10,"Antilhas Holandesas");
insert into pais values(11,"Arábia Saudita");
insert into pais values(12,"Argélia");
insert into pais values(13,"Argentina");
insert into pais values(14,"Armênia, República da");
insert into pais values(15,"Aruba");
insert into pais values(16,"Arzebaijão, República do");
insert into pais values(17,"Austrália");
insert into pais values(18,"Áustria");
insert into pais values(19,"Bahamas, Ilhas");
insert into pais values(20,"Bahrein, Ilhas");
insert into pais values(21,"Bangladesh");
insert into pais values(22,"Barbados");
insert into pais values(23,"Belarus, República da");
insert into pais values(24,"Bélgica");
insert into pais values(25,"Belize");
insert into pais values(26,"Benin");
insert into pais values(27,"Bermudas");
insert into pais values(28,"Bolívia");
insert into pais values(29,"Bósnia-Herzegovina");
insert into pais values(30,"Botsuana");
insert into pais values(31,"Brunei");
insert into pais values(32,"Bulgária, República da");
insert into pais values(33,"Burkina Faso");
insert into pais values(34,"Burundi");
insert into pais values(35,"Butão");
insert into pais values(36,"Cabo Verde, República de");
insert into pais values(37,"Camarões");
insert into pais values(38,"Camboja");
insert into pais values(39,"Canadá");
insert into pais values(40,"Canárias, Ilhas");
insert into pais values(41,"Casaquistão, República do");
insert into pais values(42,"Catar");
insert into pais values(43,"Cayman, Ilhas");
insert into pais values(44,"Chade");
insert into pais values(45,"Chile");
insert into pais values(46,"China, República Popular");
insert into pais values(47,"Chipre");
insert into pais values(48,"Christmas,Ilhas (Navidad)");
insert into pais values(49,"Cingapura");
insert into pais values(50,"Cocos-Keeling, Ilhas");
insert into pais values(51,"Colômbia");
insert into pais values(52,"Comores, Ilhas");
insert into pais values(53,"Congo");
insert into pais values(54,"Cook, Ilhas");
insert into pais values(55,"Coréia, República da");
insert into pais values(56,"Coréia, República Popular Democrática");
insert into pais values(57,"Costa do Marfim");
insert into pais values(58,"Costa Rica");
insert into pais values(59,"Coveite");
insert into pais values(60,"Croácia, República da");
insert into pais values(61,"Cuba");
insert into pais values(62,"Dinamarca");
insert into pais values(63,"Djibuti");
insert into pais values(64,"Dominica, Ilha");
insert into pais values(65,"Dubai");
insert into pais values(66,"Egito");
insert into pais values(67,"El salvador");
insert into pais values(68,"Emirados Árabes Unidos");
insert into pais values(69,"Equador");
insert into pais values(70,"Eslovaca, República");
insert into pais values(71,"Eslovênia, República da");
insert into pais values(72,"Espanha");
insert into pais values(73,"Estados Unidos");
insert into pais values(74,"Estônia, República da");
insert into pais values(75,"Etiópia");
insert into pais values(76,"Falkland (Ilhas Malvinas)");
insert into pais values(77,"Feroe, Ilhas");
insert into pais values(78,"Fezzan");
insert into pais values(79,"Fidji");
insert into pais values(80,"Filipinas");
insert into pais values(81,"Finlândia");
insert into pais values(82,"Formosa (Taiwan)");
insert into pais values(83,"França");
insert into pais values(84,"Gabão");
insert into pais values(85,"Gambia");
insert into pais values(86,"Gana");
insert into pais values(87,"Georgia, República da");
insert into pais values(88,"Gibraltar");
insert into pais values(89,"Granada");
insert into pais values(90,"Grécia");
insert into pais values(91,"Groelândia");
insert into pais values(92,"Guadalupe");
insert into pais values(93,"Guam");
insert into pais values(94,"Guatemala");
insert into pais values(95,"Guiana");
insert into pais values(96,"Guiana Francesa");
insert into pais values(97,"Guiné");
insert into pais values(98,"Guiné-Bissau");
insert into pais values(99,"Guiné-Equatorial");
insert into pais values(100,"Haiti");
insert into pais values(101,"Honduras");
insert into pais values(102,"Hong Kong");
insert into pais values(103,"Hungria, República da");
insert into pais values(104,"Iemen");
insert into pais values(105,"Índia");
insert into pais values(106,"Indonésia");
insert into pais values(107,"Inglaterra");
insert into pais values(108,"Irã, República Islâmica do");
insert into pais values(109,"Iraque");
insert into pais values(110,"Irlanda");
insert into pais values(111,"Islândia");
insert into pais values(112,"Israel");
insert into pais values(113,"Itália");
insert into pais values(114,"Iugoslávia, República Federativa da");
insert into pais values(115,"Jamaica");
insert into pais values(116,"Japão");
insert into pais values(117,"Johnston, Ilhas");
insert into pais values(118,"Jordânia");
insert into pais values(119,"Kiribati");
insert into pais values(120,"Laos, República Popular Democrática");
insert into pais values(121,"Lebuan, Ilhas");
insert into pais values(122,"Lesoto");
insert into pais values(123,"Letônia, República da");
insert into pais values(124,"Líbano");
insert into pais values(125,"Libéria");
insert into pais values(126,"Líbia");
insert into pais values(127,"Liechtenstein");
insert into pais values(128,"Lituânia, República da");
insert into pais values(129,"Luxemburgo");
insert into pais values(130,"Macau");
insert into pais values(131,"Macedônia");
insert into pais values(132,"Madagascar");
insert into pais values(133,"Malásia");
insert into pais values(134,"Malavi");
insert into pais values(135,"Maldivas");
insert into pais values(136,"Mali");
insert into pais values(137,"Malta");
insert into pais values(138,"Marianas do Norte");
insert into pais values(139,"Marrocos");
insert into pais values(140,"Marshall, Ilhas");
insert into pais values(141,"Martinica");
insert into pais values(142,"Maurício");
insert into pais values(143,"Mauritânia");
insert into pais values(144,"México");
insert into pais values(145,"Mianmar (Birmânia)");
insert into pais values(146,"Micronésia");
insert into pais values(147,"Midway, Ilhas");
insert into pais values(148,"Moçambique");
insert into pais values(149,"Moldova, República da");
insert into pais values(150,"Mônaco");
insert into pais values(151,"Mongólia");
insert into pais values(152,"Montserrat, Ilhas");
insert into pais values(153,"Namíbia");
insert into pais values(154,"Nauru");
insert into pais values(155,"Nepal");
insert into pais values(156,"Nicarágua");
insert into pais values(157,"Niger");
insert into pais values(158,"Nigéria");
insert into pais values(159,"Niue, Ilha");
insert into pais values(160,"Norfolk, Ilha");
insert into pais values(161,"Noruega");
insert into pais values(162,"Nova Caledônia");
insert into pais values(163,"Nova Zelândia");
insert into pais values(164,"Omã");
insert into pais values(165,"Pacífico, Ilhas do (administ. dos EUA)");
insert into pais values(166,"Pacífico, Ilhas do (possessão dos EUA)");
insert into pais values(167,"Países Baixos (Holanda)");
insert into pais values(168,"Palau");
insert into pais values(169,"Panamá");
insert into pais values(170,"Papua Nova Guiné");
insert into pais values(171,"Paquistão");
insert into pais values(172,"Paraguai");
insert into pais values(173,"Peru");
insert into pais values(174,"Pitcairn, Ilha de");
insert into pais values(175,"Polinésia Francesa");
insert into pais values(176,"Polônia, República da");
insert into pais values(177,"Porto Rico");
insert into pais values(178,"Portugal");
insert into pais values(179,"Quênia");
insert into pais values(180,"Quirguiz, República da");
insert into pais values(181,"Reino Unido");
insert into pais values(182,"República Centro-Africana");
insert into pais values(183,"República Dominicana");
insert into pais values(184,"Reunião, Ilha");
insert into pais values(185,"Romênia");
insert into pais values(186,"Ruanda");
insert into pais values(187,"Rússia, Federação da");
insert into pais values(188,"Saara Ocidental");
insert into pais values(189,"Salomão, Ilhas");
insert into pais values(190,"Samoa");
insert into pais values(191,"Samoa Americana");
insert into pais values(192,"San Marino");
insert into pais values(193,"Santa Helena");
insert into pais values(194,"Santa Lúcia");
insert into pais values(195,"São Cristóvão e Neves, Ilhas");
insert into pais values(196,"São Pedro e Miquelon");
insert into pais values(197,"São Tomé e Príncipe, Ilhas");
insert into pais values(198,"São Vicente e Granadinas");
insert into pais values(199,"Senegal");
insert into pais values(200,"Serra Leoa");
insert into pais values(201,"Seychelles");
insert into pais values(202,"Síria, República Árabe da");
insert into pais values(203,"Somália");
insert into pais values(204,"Sri Lanka");
insert into pais values(205,"eSwatini");
insert into pais values(206,"Sudão");
insert into pais values(207,"Suécia");
insert into pais values(208,"Suíça");
insert into pais values(209,"Suriname");
insert into pais values(210,"Tailândia");
insert into pais values(211,"Tadjiquistão, República do");
insert into pais values(212,"Tanzânia, República Unida da");
insert into pais values(213,"Tcheca, República");
insert into pais values(214,"Território Britânico no Oceano Índico");
insert into pais values(215,"Timor Leste");
insert into pais values(216,"Togo");
insert into pais values(217,"Tonga");
insert into pais values(218,"Toquelau, Ilhas");
insert into pais values(219,"Trinidad e Tobago");
insert into pais values(220,"Tunísia");
insert into pais values(221,"Turcas e caicos, Ilhas");
insert into pais values(222,"Turcomenistão, República do");
insert into pais values(223,"Turquia");
insert into pais values(224,"Tuvalu");
insert into pais values(225,"Ucrânia");
insert into pais values(226,"Uganda");
insert into pais values(227,"Uruguai");
insert into pais values(228,"Uzbequistão, República do");
insert into pais values(229,"Vanuatu");
insert into pais values(230,"Vaticano, Estado da Cidade do");
insert into pais values(231,"Venezuela");
insert into pais values(232,"Vietnã");
insert into pais values(233,"Virgens, Ilhas (Britânicas)");
insert into pais values(234,"Virgens, Ilhas (EUA)");
insert into pais values(235,"Wallis e Futuna, Ilhas");
insert into pais values(236,"Zaire");
insert into pais values(237,"Zâmbia");
insert into pais values(238,"Zimbabue");
insert into pais values(239,"Eritreia");
insert into pais values(240,"Ilha de Man");
insert into pais values(241,"Palestina");
insert into pais values(242,"Aland, Ilhas");
insert into pais values(243,"Antartica");
insert into pais values(244,"Bonaire, Saint Eustatius E Saba");
insert into pais values(245,"Bouvet, Ilha");
insert into pais values(246,"Curacao");
insert into pais values(247,"Georgia Do Sul E Sandwich Do Sul, Ilhas");
insert into pais values(248,"Guernsey");
insert into pais values(249,"Heard E Ilhas McDonald, Ilha");
insert into pais values(250,"Jersey");
insert into pais values(251,"Mayotte");
insert into pais values(252,"Montenegro");
insert into pais values(253,"Sao Bartolomeu");
insert into pais values(254,"Sao Martinho, Ilha De (Parte Francesa)");
insert into pais values(255,"Sao Martinho, Ilha De (Parte Holandesa)");
insert into pais values(256,"Servia");
insert into pais values(257,"Svalbard E Jan Mayen");
insert into pais values(258,"Sudao Do Sul");
insert into pais values(259,"Terras Austrais Francesas");

